- app/controllers/baby_materials_controller.rb
- app/models/baby_material.rb
- app/models/sale.rb
- app/models/user.rb
- app/views/baby_materials/index.html.erb
- app/views/baby_materials/new.html.erb
- app/views/baby_materials/show.html.erb
- config/routes.rb
- db/migrate/20191126102538_create_baby_materials.rb
- db/migrate/20191126131515_create_sales.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/baby_materials_controller_test.rb
- test/models/baby_material_test.rb
- test/models/sale_test.rb
mvc of baby materials + model de sale, route:
- controller: index, show, new, create
-view: index, new, show (non fini)
The seeds don't work properly
The validations are done
the schema is up to date
> mvc de babay materials + model de sale

- app/controllers/baby_materials_controller.rb
- app/models/baby_material.rb
- app/models/user.rb
- app/views/baby_materials/edit.html.erb
- app/views/baby_materials/index.html.erb
- app/views/baby_materials/show.html.erb
material controller is done, added 1 view(edit), fixed bugs
> material controller is done, added 1 view(edit), fixed bugs

- db/seeds.rb
> creation des seed

- app/models/baby_material.rb
> dependent destroy

- app/models/baby_material.rb
- db/migrate/20191127104034_add_address_to_baby_materials.rb
- db/migrate/20191127105345_change_sale_to_baby_materials.rb
- db/schema.rb
add column address and change column sale to BabyMaterial model.
> add column address and change column sale

- app/controllers/baby_materials_controller.rb
- app/views/baby_materials/new.html.erb
- app/views/baby_materials/show.html.erb
- db/seeds.rb
address seed added + controller authorization + view new  form
> address seed added + controller authorization + view new  form

- app/controllers/admin/baby_materials_controller.rb
- app/controllers/baby_materials_controller.rb
- app/views/admin/baby_materials/index.html.erb
- config/routes.rb
- test/controllers/admin/baby_materials_controller_test.rb
> dashboard 1ere partie fini

- .gitignore
- app/views/admin/baby_materials/index.html.erb
- app/views/shared/_navbar.html.erb
> link in the navbar

- Gemfile
- Gemfile.lock
- app/controllers/baby_materials_controller.rb
- app/models/baby_material.rb
- app/uploaders/photo_uploader.rb
- app/views/admin/baby_materials/index.html.erb
- app/views/baby_materials/index.html.erb
- app/views/baby_materials/new.html.erb
- app/views/baby_materials/show.html.erb
- config/routes.rb
- db/migrate/20191127150438_add_photo_to_baby_materials.rb
- db/schema.rb
cloudinary + route namespace changed
> cloudinary + route namespace changed

- app/controllers/baby_materials_controller.rb
- app/views/admin/baby_materials/index.html.erb
- app/views/baby_materials/edit.html.erb
- app/views/baby_materials/show.html.erb
- app/views/shared/_navbar.html.erb
> modified the links

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_new.scss
- app/views/baby_materials/new.html.erb
title color, align to center + button customized
> form design done

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
> footer design over

- app/assets/stylesheets/components/_new.scss
- app/views/admin/baby_materials/index.html.erb
- app/views/baby_materials/edit.html.erb
- app/views/baby_materials/new.html.erb
added some style to the forms and changed some titles:
To rent
Rented
My bookings
> added some style to the forms and changed some titles

- app/assets/stylesheets/components/_index.scss
> rectified scss index

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_new.scss
- app/views/baby_materials/edit.html.erb
- app/views/baby_materials/new.html.erb
> navbar bug fixed

- app/views/baby_materials/edit.html.erb
- app/views/baby_materials/new.html.erb
address added to edit, h2 title instead of H1 in forms + button class removed
> address added + h2 title + button class removed

- app/views/baby_materials/show.html.erb
> added buy button

- app/controllers/admin/baby_materials_controller.rb
- app/controllers/baby_materials_controller.rb
- app/controllers/sales_controller.rb
- app/views/admin/baby_materials/index.html.erb
- app/views/baby_materials/show.html.erb
- config/routes.rb
- test/controllers/sales_controller_test.rb
added transaction method
added a new nested route
added sales controller
added a simple form in show
> added transaction method

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_show.scss
- app/views/baby_materials/index.html.erb
- app/views/baby_materials/show.html.erb
> customized show

- app/controllers/baby_materials_controller.rb
- app/views/baby_materials/index.html.erb
- app/views/shared/_navbar.html.erb
added the searchbar, and it works
what changed:
-the index in the baby material controller
-the navbar
> added the searchbar, and it works

- app/controllers/baby_materials_controller.rb
i added a end of input in the index method of the baby materials controller
> i added a end of input

- app/views/admin/baby_materials/index.html.erb
- app/views/baby_materials/index.html.erb
> design title

- app/javascript/packs/application.js
- db/seeds.rb
> seed nouvelle version
